config/routes.rb
Rails.application.routes.draw do

  get "search" => "domainsearch#search", as: :domainsearch
  resources :extensions
  root 'welcome#index'

end

app/models/extension.rb
class Extension < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/domainsearch_controller.rb
class DomainsearchController < ApplicationController
  def search
    search = domainsearch_params
    if !search[:name].nil?
      extensions = Extension.all
      for ext in extensions
        # Fork off a new worker job for every extension
        logger.info(ext.inspect)
        CheckJob.new.async.perform(search[:name],ext[:name])
      end
    end
  end

  private

  # Only allow a trusted parameter "white list" through.
  def domainsearch_params
    params.permit([:name])
  end

end

app/controllers/extensions_controller.rb
class ExtensionsController < ApplicationController
  before_action :set_extension, only: [:show, :edit, :update, :destroy]

  # GET /extensions
  def index
    @extensions = Extension.all
  end

  # GET /extensions/1
  def show
  end

  # GET /extensions/new
  def new
    @extension = Extension.new
  end

  # GET /extensions/1/edit
  def edit
  end

  # POST /extensions
  def create
    @extension = Extension.new(extension_params)

    if @extension.save
      redirect_to extensions_url, notice: 'Extension was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /extensions/1
  def update
    if @extension.update(extension_params)
      redirect_to extensions_url, notice: 'Extension was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /extensions/1
  def destroy
    @extension.destroy
    redirect_to extensions_url, notice: 'Extension was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_extension
      @extension = Extension.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def extension_params
      params.require(:extension).permit([:name])
    end
end

app/controllers/task_controller.rb
class TaskController < WebsocketRails::BaseController
	def completed_notfound
		logger.info("NOT FOUND " + message.inspect)
	end
	def completed_found
		logger.info("FOUND " + message.inspect)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@extensions = Extension.all.order("name asc")
		redirect_to extensions_path if (@extensions.nil? or @extensions == [])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domainsearch_helper.rb
module DomainsearchHelper
end

app/helpers/extensions_helper.rb
module ExtensionsHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/domainsearch/search.js.erb
$('#spinner').show();

app/views/extensions/_form.html.erb
<% if @extension.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@extension.errors.count, "error") %> prohibited this extension from being saved:</h2>

    <ul>
      <% @extension.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

  </div>
<% end %>


<%= simple_form_for(@extension, html: { class: 'form-horizontal' }) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :value=> "#{f.object.new_record? ? "Create extension" : "Update extension"}", :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/extensions/edit.html.erb
<h1>Edit extension</h1>

<%= render 'form' %>


<%= link_to fa_icon("info-circle",:text=>"Show" ), @extension,:class=>"btn btn-primary" %> 
<%= link_to fa_icon("arrow-left",:text=>'Back'), extensions_path,:class=>"btn btn-info" %>

app/views/extensions/index.html.erb
<h1>Extensions</h1>

<%= link_to fa_icon("plus-circle",:text=>'New Extension'), new_extension_path, :class=>"btn btn-primary btn-large" %>

<br>

<table class="table table-striped nowrap datatable">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @extensions.each do |extension| %>
      <tr>
        <td><%= SimpleIDN.to_unicode(extension[:name].downcase) %></td>
        <td><%= link_to (fa_icon "info-circle",:text=>"Show") , extension,:class=>"btn btn-primary" %></td>
        <td><%= link_to (fa_icon "edit",:text=>"Edit" ), edit_extension_path(extension),:class=>"btn btn-warning" %></td>
        <td><%= link_to (fa_icon "trash-o",:text=>"Delete" ), extension, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/extensions/new.html.erb
<h1>New extension</h1>

<%= render 'form' %>

<br>

<%= link_to fa_icon("arrow-left",:text=>'Back'), extensions_path,:class=>"btn btn-info" %>

app/views/extensions/show.html.erb
<p id="notice"><%= notice %></p>

<dl class="dl-horizontal">
</dl>

<%= extension[:name] %>

<%= link_to fa_icon("edit",:text=>"Edit" ), edit_extension_path(@extension),:class=>"btn btn-warning" %>
<%= link_to fa_icon("arrow-left",:text=>'Back'), extensions_path,:class=>"btn btn-info" %>

app/views/layouts/_messages.html.erb
<% if !request.nil? %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
     </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>RailsParallelDomainChecker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
    	  <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
	      <%= render 'layouts/messages' %>
	      <div class="container">
	      	<%= yield %>
	  	  </div>
    </main>
	<footer>
		<p class="newscycle lightcolor">&copy; <%= Date.today.year.to_s %> </p>
	</footer>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
<h1>Search domainnames</h1>
<P>Search for many domain name extensions at once. Enter a name without the extension to search all available extensions. </p>

<%= form_tag domainsearch_path, {method: :get, :class => "form-inline", :remote=>true } do %>
  <div class="form-group">
    <label class="sr-only" for="searchdomain">Name to search</label>
    <div class="input-group">
      <div class="input-group-addon">www.</div>
      <input type="text" class="form-control" name="name" id="searchdomain" placeholder="Name-to-find">
      <div class="input-group-addon">.???</div>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Search</button>
<% end %>
</div>

<i class="icon-spinner icon-spin"></i>
<div id="searchresults">
  <table class="table table-striped">
    <thead>
      <tr><th>TLD</th><th>Domain name</th><th>Result</th></tr>
    </thead>
    <tbody>
<%
	i = 0
	for ext in @extensions
%>
  <tr id="row_<%= ext[:name] %>">
		<td><%= SimpleIDN.to_unicode(ext[:name].downcase) %></td>
	  <td id="name_<%= ext[:name] %>"></td>
	  <td id="searchres_<%= ext[:name] %>"></td>
  </tr>
<%
	end
%>
  </tbody>
</table>

</div>